apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/mohsen-abbas/node-express-hello-world-k8s.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

