# kubernetes/hello-world-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: demo-app
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      annotations:
        # Environment variable export template
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'hello-world'
        vault.hashicorp.com/agent-update: 'true'
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/agent-inject-secret-config: 'secret/hello-world-secret'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/hello-world-secret" -}}
          {{- range $key, $value := .Data }}
          export {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end }}
      labels:
        app: hello-world
    spec:
      serviceAccountName: hello-world
      containers:
      - name: hello-world-container
        image: us-central1-docker.pkg.dev/my-demo-project-434216/my-demo-registry/hello_world:32dac96936451bdad147a4e86e1c4825be80de22
        command: ["/bin/sh", "-c"]
        args: [". /vault/secrets/config && node app.js"]
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "128Mi"

